### ISSUE TITLE
Alias tips

### ISSUE THREAD

**Issue by tagraf** [gargolito/search-pypi#3]
Alias search-pypi.py as pipsearch for ease of memory.

Edit your `~/.bashrc`
Go to the very bottom of the page, then add:
`alias pipsearch='/PATH-TO-THE-FILE/search-pypi/search-pypi.py'` (Make sure you put down the correct directory path to your script file)
Save your `~/.bashrc`
Run `source ~/.bashrc`
Then test out by running `pipsearch hello`

Just in case whenever you typed down `pip search hello` and just when you encounter the error, then hopefully you'll start remembering that you have the script in the background and you can just concatenate it as `pipsearch` to quickly search it.

**Comment by gargolito** [comment]
Thanks for the input, I actually have a bash (sourced from a bashrc file) function that replaces "pip search" and uses my script. It's fairly straight forward. You can add to your bashrc, or if you're like me, you have a separate bashrc file for your functions (~/.bash_functions) that is sourced from bashrc. Anyhow, here it is:
```
pip () {
    search="/path/to/search-pypi.py" # <<< CHANGE
    if [[ "$1" == "search" ]]; then
        shift;
        ${search} $@;
    else
        pip $@;
    fi
}
```

I just wrote it from memory and it needs some checks, but it should work.

I did not include that because it's sort of a personal preference for most. I might turn this into a pip installable package if there's enough interest. Or I could add an install script but that gets dicey because people may be using different types of python environment managers like pyenv, conda, etc...
